version: 2

sources:
  - name: bronze
    description: "Fonte bruta catalogada no Glue Data Catalog a partir da camada Bronze no S3."
    database: awsdatacatalog
    schema: technova_db
    tables:
      - name: vendas
        description: "Tabela de vendas catalogada pelo Glue Crawler."